version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'

  worker:
    build: ./worker
    container_name: worker
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - backend
    env_file:
      - ./worker/.env

  collector:
    build: ./collector
    container_name: collector
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - ./collector/.env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - '5173:5173'

volumes:
  mongo_data:
